# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#  --scheme GitHubRepositories --workspace GitHubRepositories.xcworkspace --show ./GitHubRepositories.xcodeproj/./GitHubRepositories.xcodeproj

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs slather coverage tests"
  lane :coverage_lane do
     
     slather(
       	input_format: "xml",
       	scheme: "GitHubRepositories",
       	workspace: "GitHubRepositories.xcworkspace",
	proj: "GitHubRepositories.xcodeproj"
     )
  
  end
end
